#!/bin/bash

## Check options
syncDirs=false
gitInit=false
bbUser=
gitRAdd=false
gitAC=false
cMsg=
gitPush=false
clone=false
pull=false

while [ "$1" != "" ]; do
    case $1 in
        -u | --user )           shift
                                bbUser=$1
				echo -n Bitbucket Password: 
				read -s password
				echo
				;;
	-r | --remote-add )	gitRAdd=true
                                ;;
        -s | --sync )           syncDirs=true
                                ;;
        -i | --git-init )       gitInit=true
                                ;;
        -c | --git-commit )     gitAC=true
                                ;;
        -m | —commit-message )  shift
                                cMsg=$1
				;;
        -p | --git-push )       gitPush=true
                                ;;
	--clone )		clone=true
				;;
	--pull )		pull=true
				;;
    esac
    shift
done

for ((i = 1; i < 15; ++i)); do
    group="ayed2017-grupo$i"

    if [ $clone = true ] && [ $bbUser != "" ]; then
	remote="https://$bbUser:$password@bitbucket.org/$bbUser/$group.git"
	echo "### Cloning $group ###"
	git clone $remote
    elif [ $pull = true ] && [ $bbUser != "" ]; then
        echo "### Pulling from $group ###"
	cd $group
        git pull origin master
	cd ..
    else
    
    	if [ $syncDirs = true ]; then
        	echo "### Copying project structure for $group ###"
        	rsync -rv --exclude '.git' --exclude '*.sh' ayed2017/ ayed2017-grupo$i
    	fi

    	echo "### Entering $group ###"
    	cd $group

    	if [ $gitInit = true ]; then
        	echo "### Setting up git repo ###"
        	git init
    	fi

    	if [ $gitRAdd = true ]; then
		echo "### Adding remote [$remote] ###"
		remote="https://$bbUser:$password@bitbucket.org/$bbUser/$group.git"
        	git remote add origin $remote
    	fi

    	if [ $gitAC = true ]; then
        	echo "### Committing ###"
        	git add .
        	git commit -m “$cMsg”
    	fi

    	if [ $gitPush = true ]; then
        	echo "### Pushing ###"
		git push origin master
    	fi

    	echo "### Exiting $group ###"
    	cd ..

    fi
done
